[phases.setup]
nixPkgs = ["python311", "ffmpeg", "pip"]

[phases.install]
cmds = [
  "python3 -m ensurepip --upgrade",
  "python3 -m pip install --upgrade pip",
  "pip3 install -r requirements.txt"
]

[start]
cmd = "python3 run.py"
